"""empty message

Revision ID: 9fd7a085319b
Revises: 8d2b844a6cec
Create Date: 2021-07-22 00:43:46.429940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd7a085319b'
down_revision = '8d2b844a6cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_venue_id_fkey', 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'artist_id')
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Shows_venue_id_fkey', 'Shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Shows', 'id')
    # ### end Alembic commands ###
